version: '3'
services:
  db:
    image: mysql:5.6
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=mygame
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    expose:
      - "3306"
