version: '3'
services:
  db:
    image: mysql:latest
    container_name: myg_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=mygame
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    expose:
      - "3306"
    volumes:
      - ./:/app/myG
      - /data/myG:/var/lib/mysql
  redis:
    image: redis:latest
    container_name: myg_redis
    restart: always
    ports:
        - 6379:6379
    volumes:
        - ./config/redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]
    expose:
      - "6379"
  nats:
    image: nats
    container_name: myg_nats
    restart: always
    ports:
        - '4222:4222'
    expose:
      - "4222"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    container_name: myg_elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
    ports:
      - "9200:9200"
    networks:
      - elastic
  kibana:
    image: docker.elastic.co/kibana/kibana:7.7.0
    container_name: myg_kibana
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "xpack.graph.enabled=false"
      - "xpack.ml.enabled=false"
      - "xpack.monitoring.enabled=false"
      - "xpack.reporting.enabled=false"
      - "xpack.watcher.enabled=false"
    ports:
      - 5601:5601
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    networks:
      - elastic

networks:
  elastic:
    driver: bridge