---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.proxysql.admin.port }}
      protocol: TCP
      name: proxysql-admin
    - port: {{ .Values.mysql.port }}
      protocol: TCP
      name: proxysql-sql
  selector:
    app: {{ template "fullname" . }}
{{- $root := . }}
{{- range $i, $e := until (int .Values.numReplicas) }}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
    app: {{ template "fullname" $root }}
    chart: "{{ $root.Chart.Name }}-{{ $root.Chart.Version }}"
    release: "{{ $root.Release.Name }}"
    heritage: "{{ $root.Release.Service }}"
  name: {{ template "fullname" $root }}-announce-{{ $e }}
spec:
  ports:
    - name: proxysql-admin
      port: {{ $root.Values.proxysql.admin.port }}
      protocol: TCP
      targetPort: {{ $root.Values.proxysql.admin.port }}
  publishNotReadyAddresses: true
  selector:
    app: {{ template "fullname" $root }}
    statefulset.kubernetes.io/pod-name: {{ template "fullname" $root }}-{{ $e }}
  type: ClusterIP
{{- end }}