name: proxysql-cluster
version: 2.0.0
description: Chart for ProxySQL Cluster
keywords:
- mysql
- database
- proxysql
- cluster
home: http://www.proxysql.com/
sources:
- https://github.com/sysown/proxysql
maintainers:
- name: Jeremy Xu
  email: jeremyxu2010@gmail.com
engine: gotpl
