'use strict'

/** @type {import('@adonisjs/lucid/src/Schema')} */
const Schema = use('Schema')

class Import_dummy_data_Schema extends Schema {
  up () {
    this
    .raw("insert into groups (name, user_id, group_img, game_names_id, grp_description, verified, created_at, updated_at) select 'Dota 2 - myG Official', 1, 'https://static-cdn.jtvnw.net/ttv-boxart/Dota%202-1080x1600.jpg', id, 'Offical community, hosted by myG', 1, '1988-08-08', '1988-08-08' from game_names where game_name = \"Dota 2\" ")
    .raw("insert into groups (name, user_id, group_img, game_names_id, grp_description, verified, created_at, updated_at) select 'Clash Royale - myG Official', 1, 'https://static-cdn.jtvnw.net/ttv-boxart/Clash%20Royale-1080x1600.jpg', id, 'Offical community, hosted by myG', 1, '1988-08-08', '1988-08-08' from game_names where game_name = \"Clash Royale\" ")
    .raw("insert into groups (name, user_id, group_img, game_names_id, grp_description, verified, created_at, updated_at) select 'Call of Duty: Warzone - myG Official', 1, 'https://static-cdn.jtvnw.net/ttv-boxart/Call%20of%20Duty:%20Warzone-1080x1600.jpg', id, 'Offical community, hosted by myG', 1, '1988-08-08', '1988-08-08' from game_names where game_name = \"Call of Duty: Warzone\" ")
    .raw("insert into groups (name, user_id, group_img, game_names_id, grp_description, verified, created_at, updated_at) select 'Apex Legends - myG Official', 1, 'https://static-cdn.jtvnw.net/ttv-boxart/Mobile%20Legends:%20Bang%20bang-1080x1600.jpg', id, 'Offical community, hosted by myG', 1, '1988-08-08', '1988-08-08' from game_names where game_name = \"Apex Legends\" ")
    .raw("insert into groups (name, user_id, group_img, game_names_id, grp_description, verified, created_at, updated_at) select 'CSGO - myG Official', 1, 'https://static-cdn.jtvnw.net/ttv-boxart/Counter-Strike:%20Global%20Offensive-1080x1600.jpg', id, 'Offical community, hosted by myG', 1, '1988-08-08', '1988-08-08' from game_names where game_name = \"CSGO\" ")
    .raw("insert into groups (name, user_id, group_img, game_names_id, grp_description, verified, created_at, updated_at) select 'Fortnite - myG Official', 1, 'https://static-cdn.jtvnw.net/ttv-boxart/Fortnite-1080x1600.jpg', id, 'Offical community, hosted by myG', 1, '1988-08-08', '1988-08-08' from game_names where game_name = \"Fortnite\" ")
    .raw("insert into groups (name, user_id, group_img, game_names_id, grp_description, verified, created_at, updated_at) select 'Minecraft - myG Official', 1, 'https://static-cdn.jtvnw.net/ttv-boxart/Minecraft-1080x1600.jpg', id, 'Offical community, hosted by myG', 1, '1988-08-08', '1988-08-08' from game_names where game_name = \"Minecraft\" ")
    .raw("insert into groups (name, user_id, group_img, game_names_id, grp_description, verified, created_at, updated_at) select 'Mobile Legends: Bang Bang - myG Official', 1, 'https://static-cdn.jtvnw.net/ttv-boxart/Mobile%20Legends:%20Bang%20bang-1080x1600.jpg', id, 'Offical community, hosted by myG', 1, '1988-08-08', '1988-08-08' from game_names where game_name = \"Mobile Legends: Bang Bang\" ")
    .raw("insert into groups (name, user_id, group_img, game_names_id, grp_description, verified, created_at, updated_at) select 'NBA 2K - myG Official', 1, 'https://static-cdn.jtvnw.net/ttv-boxart/NBA%202K20-1080x1600.jpg', id, 'Offical community, hosted by myG', 1, '1988-08-08', '1988-08-08' from game_names where game_name = \"NBA 2K\" ")
    .raw("insert into groups (name, user_id, group_img, game_names_id, grp_description, verified, created_at, updated_at) select 'Overwatch - myG Official', 1, 'https://static-cdn.jtvnw.net/ttv-boxart/Overwatch-1080x1600.jpg', id, 'Offical community, hosted by myG', 1, '1988-08-08', '1988-08-08' from game_names where game_name = \"Overwatch\" ")
    .raw("insert into groups (name, user_id, group_img, game_names_id, grp_description, verified, created_at, updated_at) select 'PUBG - myG Official', 1, 'https://static-cdn.jtvnw.net/ttv-boxart/PLAYERUNKNOWN%27S%20BATTLEGROUNDS-1080x1600.jpg', id, 'Offical community, hosted by myG', 1, '1988-08-08', '1988-08-08' from game_names where game_name = \"PUBG\" ")
    .raw("insert into groups (name, user_id, group_img, game_names_id, grp_description, verified, created_at, updated_at) select 'Pokemon GO - myG Official', 1, 'https://static-cdn.jtvnw.net/ttv-boxart/Pok%C3%A9mon%20Go-1080x1600.jpg', id, 'Offical community, hosted by myG', 1, '1988-08-08', '1988-08-08' from game_names where game_name = \"Pokemon GO\" ")
    .raw("insert into groups (name, user_id, group_img, game_names_id, grp_description, verified, created_at, updated_at) select 'Roblox - myG Official', 1, 'https://static-cdn.jtvnw.net/ttv-boxart/ROBLOX-1080x1600.jpg', id, 'Offical community, hosted by myG', 1, '1988-08-08', '1988-08-08' from game_names where game_name = \"Roblox\" ")
    .raw("insert into groups (name, user_id, group_img, game_names_id, grp_description, verified, created_at, updated_at) select 'Rocket League - myG Official', 1, 'https://static-cdn.jtvnw.net/ttv-boxart/Rocket%20League-1080x1600.jpg', id, 'Offical community, hosted by myG', 1, '1988-08-08', '1988-08-08' from game_names where game_name = \"Rocket League\" ")
    .raw("insert into groups (name, user_id, group_img, game_names_id, grp_description, verified, created_at, updated_at) select 'Subway Surfers - myG Official', 1, 'https://myG.gg/platform_images/Game+Images/subwaysurfers.jpg', id, 'Offical community, hosted by myG', 1, '1988-08-08', '1988-08-08' from game_names where game_name = \"Subway Surfers\" ")
    .raw("insert into groups (name, user_id, group_img, game_names_id, grp_description, verified, created_at, updated_at) select 'Super Smash Bros. Ultimate - myG Official', 1, 'https://static-cdn.jtvnw.net/ttv-boxart/Super%20Smash%20Bros.%20Ultimate-1080x1600.jpg', id, 'Offical community, hosted by myG', 1, '1988-08-08', '1988-08-08' from game_names where game_name = \"Super Smash Bros. Ultimate\" ")
    .raw("insert into groups (name, user_id, group_img, game_names_id, grp_description, verified, created_at, updated_at) select 'League of Legends - myG Official', 1, 'https://static-cdn.jtvnw.net/ttv-boxart/League%20of%20Legends-1080x1600.jpg', id, 'Offical community, hosted by myG', 1, '1988-08-08', '1988-08-08' from game_names where game_name = \"League of Legends\" ")
    .raw("insert into groups (name, user_id, group_img, game_names_id, grp_description, verified, created_at, updated_at) select 'Grand Theft Auto V - myG Official', 1, 'https://static-cdn.jtvnw.net/ttv-boxart/Grand%20Theft%20Auto%20V-1080x1600.jpg', id, 'Offical community, hosted by myG', 1, '1988-08-08', '1988-08-08' from game_names where game_name = \"Grand Theft Auto V\" ")
    .raw("insert into groups (name, user_id, group_img, game_names_id, grp_description, verified, created_at, updated_at) select 'Valorant - myG Official', 1, 'https://static-cdn.jtvnw.net/ttv-boxart/VALORANT-1080x1600.jpg', id, 'Offical community, hosted by myG', 1, '1988-08-08', '1988-08-08' from game_names where game_name = \"Valorant\" ")
    .raw("insert into groups (name, user_id, group_img, game_names_id, grp_description, verified, created_at, updated_at) select 'World of Warcraft - myG Official', 1, 'https://static-cdn.jtvnw.net/ttv-boxart/World%20of%20Warcraft-1080x1600.jpg', id, 'Offical community, hosted by myG', 1, '1988-08-08', '1988-08-08' from game_names where game_name = \"World of Warcraft\" ")
    .raw("insert into groups (name, user_id, group_img, game_names_id, grp_description, verified, created_at, updated_at) select 'Hearthstone - myG Official', 1, 'https://static-cdn.jtvnw.net/ttv-boxart/Hearthstone-1080x1600.jpg', id, 'Offical community, hosted by myG', 1, '1988-08-08', '1988-08-08' from game_names where game_name = \"Hearthstone\" ")
    .raw("insert into groups (name, user_id, group_img, game_names_id, grp_description, verified, created_at, updated_at) select 'Fall Guys: Ultimate Knockout - myG Official', 1, 'https://static-cdn.jtvnw.net/ttv-boxart/Fall%20Guys-1080x1600.jpg', id, 'Offical community, hosted by myG', 1, '1988-08-08', '1988-08-08' from game_names where game_name = \"Fall Guys: Ultimate Knockout\" ")
    .raw("insert into groups (name, user_id, group_img, game_names_id, grp_description, verified, created_at, updated_at) select 'World of Tanks - myG Official', 1, 'https://static-cdn.jtvnw.net/ttv-boxart/World%20of%20Tanks-1080x1600.jpg', id, 'Offical community, hosted by myG', 1, '1988-08-08', '1988-08-08' from game_names where game_name = \"World of Tanks\" ")
    .raw("insert into groups (name, user_id, group_img, game_names_id, grp_description, verified, created_at, updated_at) select 'Baldurs Gate 3 - myG Official', 1, 'https://steamcdn-a.akamaihd.net/steam/apps/1086940/header.jpg', id, 'Offical community, hosted by myG', 1, '1988-08-08', '1988-08-08' from game_names where game_name = \"Baldurs Gate 3\" ")
    .raw("insert into groups (name, user_id, group_img, game_names_id, grp_description, verified, created_at, updated_at) select 'StarCraft - myG Official', 1, 'https://static-cdn.jtvnw.net/ttv-boxart/StarCraft-1080x1600.jpg', id, 'Offical community, hosted by myG', 1, '1988-08-08', '1988-08-08' from game_names where game_name = \"StarCraft\" ")
    .raw("insert into groups (name, user_id, group_img, game_names_id, grp_description, verified, created_at, updated_at) select 'StarCraft II - myG Official', 1, 'https://static-cdn.jtvnw.net/ttv-boxart/StarCraft%20II-1080x1600.jpg', id, 'Offical community, hosted by myG', 1, '1988-08-08', '1988-08-08' from game_names where game_name = \"StarCraft II\" ")
    .raw("insert into groups (name, user_id, group_img, game_names_id, grp_description, verified, created_at, updated_at) select 'League of Legends: Wild Rift - myG Official', 1, 'https://static-cdn.jtvnw.net/ttv-boxart/League%20of%20Legends:%20Wild%20Rift-1080x1600.jpg', id, 'Offical community, hosted by myG', 1, '1988-08-08', '1988-08-08' from game_names where game_name = \"League of Legends: Wild Rift\" ")
    .raw("insert into groups (name, user_id, group_img, game_names_id, grp_description, verified, created_at, updated_at) select 'Among Us - myG Official', 1, 'https://static-cdn.jtvnw.net/ttv-boxart/Among%20Us-1080x1600.jpg', id, 'Offical community, hosted by myG', 1, '1988-08-08', '1988-08-08' from game_names where game_name = \"Among Us\" ")
    .raw("insert into groups (name, user_id, group_img, game_names_id, grp_description, verified, created_at, updated_at) select 'Cyberpunk 2077 - myG Official', 1, 'https://static-cdn.jtvnw.net/ttv-boxart/Cyberpunk%202077-1080x1600.jpg', id, 'Offical community, hosted by myG', 1, '1988-08-08', '1988-08-08' from game_names where game_name = \"Cyberpunk 2077\" ")
    .raw("insert into groups (name, user_id, group_img, game_names_id, grp_description, verified, created_at, updated_at) select 'Heroes of the Storm - myG Official', 1, 'https://static-cdn.jtvnw.net/ttv-boxart/Heroes%20of%20the%20Storm-1080x1600.jpg', id, 'Offical community, hosted by myG', 1, '1988-08-08', '1988-08-08' from game_names where game_name = \"Heroes of the Storm\" ")
    .raw("insert into groups (name, user_id, group_img, game_names_id, grp_description, verified, created_at, updated_at) select 'Tom Clancys Rainbow Six Siege - myG Official', 1, 'https://static-cdn.jtvnw.net/ttv-boxart/Tom%20Clancy%27s%20Rainbow%20Six%20Siege-1080x1600.jpg', id, 'Offical community, hosted by myG', 1, '1988-08-08', '1988-08-08' from game_names where game_name = \"Tom Clancys Rainbow Six Siege\" ")
    .raw("insert into groups (name, user_id, group_img, game_names_id, grp_description, verified, created_at, updated_at) select 'Magic: The Gathering - myG Official', 1, 'https://static-cdn.jtvnw.net/ttv-boxart/Magic:%20The%20Gathering-1080x1600.jpg', id, 'Offical community, hosted by myG', 1, '1988-08-08', '1988-08-08' from game_names where game_name = \"Magic: The Gathering\" ")



  }

  down () {

  }
}

module.exports = Import_dummy_data_Schema
