apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mygame.fullname" . }}
  labels: {{- include "mygame.labels" . | nindent 4 }}
type: Opaque
data:
  db-password: {{ ternary (randAlphaNum 10) .Values.mygame.databasePassword (empty .Values.mygame.databasePassword) | b64enc | quote }}
  appkey: {{ ternary (randAlphaNum 10) .Values.mygame.appKey (empty .Values.mygame.appKey) | b64enc | quote }}
  awskey: {{ ternary (randAlphaNum 10) .Values.mygame.awsKey (empty .Values.mygame.awsKey) | b64enc | quote }}
  awssecret: {{ ternary (randAlphaNum 10) .Values.mygame.awsSecret (empty .Values.mygame.awsSecret) | b64enc | quote }}
  googleid: {{ ternary (randAlphaNum 10) .Values.mygame.googleID (empty .Values.mygame.googleID) | b64enc | quote }}
  googlesecret: {{ ternary (randAlphaNum 10) .Values.mygame.googleSecret (empty .Values.mygame.googleSecret) | b64enc | quote }}
  facebookid: {{ ternary (randAlphaNum 10) .Values.mygame.facebookID (empty .Values.mygame.facebookID) | b64enc | quote }}
  facebooksecret: {{ ternary (randAlphaNum 10) .Values.mygame.facebookSecret (empty .Values.mygame.facebookSecret) | b64enc | quote }}
  mixgooglemapskey: {{ ternary (randAlphaNum 10) .Values.mygame.mixGoogleMapsKey (empty .Values.mygame.mixGoogleMapsKey) | b64enc | quote }}
  secretkey: {{ ternary (randAlphaNum 10) .Values.mygame.secretKey (empty .Values.mygame.secretKey) | b64enc | quote }}
  sitekey: {{ ternary (randAlphaNum 10) .Values.mygame.siteKey (empty .Values.mygame.siteKey) | b64enc | quote }}
  translatekey: {{ ternary (randAlphaNum 10) .Values.mygame.translateKey (empty .Values.mygame.translateKey) | b64enc | quote }}
  slackbasekey: {{ ternary (randAlphaNum 10) .Values.mygame.slackbasekey (empty .Values.mygame.slackbasekey) | b64enc | quote }}
  

---
{{- if .Values.tls.enabled -}}
{{- $_ := required "Fullchain PEM cannot be empty" $.Values.tls.fullchain }}
{{- $_ := required "Private key pem cannot be empty." $.Values.tls.privkey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tls.name }}
type: Opaque
data:
  tls.crt: {{ .Values.tls.fullchain | b64enc }}
  tls.key: {{ .Values.tls.privkey | b64enc }}
{{- end }}
