apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mygame.fullname" . }}
  labels: {{- include "mygame.labels" . | nindent 4 }}
type: Opaque
data:
  db-password: {{ ternary (randAlphaNum 10) .Values.mygame.databasePassword (empty .Values.mygame.databasePassword) | b64enc | quote }}
  appkey: {{ ternary (randAlphaNum 10) .Values.mygame.appKey (empty .Values.mygame.appKey) | b64enc | quote }}
  awskey: {{ ternary (randAlphaNum 10) .Values.mygame.awsKey (empty .Values.mygame.awsKey) | b64enc | quote }}
  awssecret: {{ ternary (randAlphaNum 10) .Values.mygame.awsSecret (empty .Values.mygame.awsSecret) | b64enc | quote }}
  googleid: {{ ternary (randAlphaNum 10) .Values.mygame.googleID (empty .Values.mygame.googleID) | b64enc | quote }}
  googlesecret: {{ ternary (randAlphaNum 10) .Values.mygame.googleSecret (empty .Values.mygame.googleSecret) | b64enc | quote }}
---
{{- if .Values.tls.enabled -}}
{{- $_ := required "Fullchain PEM cannot be empty" $.Values.tls.fullchain }}
{{- $_ := required "Private key pem cannot be empty." $.Values.tls.privkey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tls.name }}
type: Opaque
data:
  tls.crt: {{ .Values.tls.fullchain | b64enc }}
  tls.key: {{ .Values.tls.privkey | b64enc }}
{{- end }}
