{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "mariadb-galera.serviceAccountName" . }}
  labels: {{- include "mariadb-galera.labels" . | nindent 4 }}
{{- end }}
