apiVersion: v1
kind: Pod
metadata:
  name: {{ template "mariadb-galera.fullname" . }}-test-{{ randAlphaNum 5 | lower }}
  annotations:
    "helm.sh/hook": test-success
spec:
  initContainers:
    - name: "test-framework"
      image: "dduportal/bats:0.4.0"
      command:
        - "bash"
        - "-c"
        - |
          set -ex
          # copy bats to tools dir
          cp -R /usr/local/libexec/ /tools/bats/
      volumeMounts:
        - mountPath: /tools
          name: tools
  containers:
    - name: mariadb-galera-test
      image: {{ template "mariadb-galera.image" . }}
      imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
      command: ["/tools/bats/bats", "-t", "/tests/run.sh"]
      env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
            {{- if .Values.existingSecret }}
              name: {{ .Values.existingSecret }}
            {{- else }}
              name: {{ template "mariadb-galera.fullname" . }}
            {{- end }}
              key: mariadb-galera-root-password
      volumeMounts:
        - mountPath: /tests
          name: tests
          readOnly: true
        - mountPath: /tools
          name: tools
  volumes:
    - name: tests
      configMap:
        name: {{ template "mariadb-galera.fullname" . }}-tests
    - name: tools
      emptyDir: {}
  restartPolicy: Never
