# Default values for mygame.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

mygame:
  databaseName: mygame
  databaseHost: galera-mariadb-galera
  databasePort: 3306
  orgUrl: https://myg.gg
  smtpHost: smtp.gmail.com
  smtpPort: 587
  smtpFromAddress: noreply@myG.gg
  nodeEnvironment: production
  redisHost: 'redis-redis-cluster-headless'
  redisPort: '"6379"'
  natsServer: 'nats://nats-client:4222'
  clamavHost: clamav
  clamavPort: '"3310"'
  timezone: UTC
  features_on:
  awsSesRegion: us-east-1
  facebookID: '522599251611585'
  elasticSearch2: http://elasticsearch-master:9200
  elasticSearch: http://elasticsearch-master:9200

image:
  repository: myg2020/myg
  tag: latest
  pullPolicy: Always

imagePullSecrets:
  - name: mygame-dockerhub
nameOverride: ''
fullnameOverride: ''

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  portName: mygame-http
  port: 3333
  targetPort: 3333
  annotations: {}

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    #cert-manager.io/cluster-issuer: myg
    #ingress.kubernetes.io/force-ssl-redirect: 'true'
    #kubernetes.io/tls-acme: "true"
  paths: []
  path: /
  hostName: myg.gg
  #tls:
  #  - secretName: myg.gg
  #    hosts:
  #      - myg.gg

ingress2:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: myg-www
    ingress.kubernetes.io/force-ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($request_uri ~* \.(ico|css|js|gif|jpe?g|png|svg)) {
            expires 2d;
            add_header Pragma public;
            add_header Cache-Control "public";
            break;
      }
    #kubernetes.io/tls-acme: "true"
  paths: []
  path: /
  hostName: www.myg.gg
  tls:
    - secretName: www.myg.gg
      hosts:
        - www.myg.gg

tls:
  enabled: false
  name: mygggsecret
  fullchain: |-
  privkey: |-

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
