# values.yaml

# Docker image to use for deployment
image:
  repository: "proxysql/proxysql"
  tag: "latest"

# Default number of ProxySQL replicas
numReplicas: 2

# Default admin username
proxysql:
  admin:
    username: admin
    password: admin
    # Connect on this port to administer ProxySQL, view stats, etc.
    iface: "0.0.0.0"
    port: 6032
  clusterAdmin:
    username: cluster1
    password: secret1pass
  # Query Cache Size
  # queryCacheSizeMb: 256
  # ProxySQL needs a cluster name
  dataDir: "/var/lib/proxysql"
  webEnabled: true
  monitorConfigChange: false
  #  additionConfig: ""
  additionConfig: |
    mysql_servers =
    (
       { address="galera-mariadb-galera-0", port=3306 , hostgroup=1, max_connections=2048 },
       { address="galera-mariadb-galera-1", port=3306 , hostgroup=1, max_connections=2048 },
       { address="galera-mariadb-galera-2", port=3306 , hostgroup=2, max_connections=2048 },
    )
    mysql_group_replication_hostgroups =
    (
      { writer_hostgroup=1 , reader_hostgroup=2, active=1, max_writers=1, writer_is_also_reader=1, max_transactions_behind=100 }
    )
    mysql_users =
    (
       { username = "root" , password = "rootpass" , default_hostgroup = 1 , active = 1 }
    )
    mysql_query_rules =
    (
      {
        rule_id=100
        active=1
        match_pattern="^SELECT .* FOR UPDATE"
        destination_hostgroup=1
        apply=1
      },
      {
        rule_id=200
        active=1
        match_pattern="^SELECT .*"
        destination_hostgroup=2
        apply=1
      },
      {
        rule_id=300
        active=1
        match_pattern=".*"
        destination_hostgroup=1
        apply=1
      }
    )
# MySQL Settings
mysql:
  # Applications connect on this port to run queries
  iface: "0.0.0.0"
  port: 6033
  # This is the monitor user, just needs usage rights on the databases
  monitor:
    username: monitor
    password: monitor
  admin:
    username: root
    password: insecurepassword

# Resource requests and limits
resources: {}
#resources:
#  requests:
#    memory: "128Mi"
#    cpu: "100m"
#  limits:
#    memory: "512Mi"
#    cpu: "500m"

# Optional tolerations
tolerations: {}
